# Generated by Django 2.1 on 2018-09-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='endTime',
            field=models.TimeField(max_length=6),
        ),
        migrations.AlterField(
            model_name='routine',
            name='startTime',
            field=models.TimeField(max_length=6),
        ),
    ]
