# Generated by Django 2.1 on 2018-09-28 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0005_auto_20180927_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField()),
                ('fingerprint', models.TextField()),
                ('finger_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Fingerprints',
            },
        ),
        migrations.CreateModel(
            name='Student_Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField(unique=True)),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Group')),
            ],
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Student_module',
        ),
        migrations.RemoveField(
            model_name='results',
            name='module',
        ),
        migrations.RemoveField(
            model_name='results',
            name='student',
        ),
        migrations.RemoveField(
            model_name='users',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.RemoveField(
            model_name='attendance_detail',
            name='attendance_detail_id',
        ),
        migrations.RemoveField(
            model_name='attendance_detail',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='attendance_detail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance_detail',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enroll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='attendance_detail',
            name='entry_datetime',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance_detail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='module_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_module',
            name='class_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Lab', 'Lab'), ('Tutorial and Lab', 'Tutorial and Lab')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='period',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='class_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Lab', 'Lab')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='routine',
            name='day_of_the_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thrusday', 'Thrusday'), ('Friday', 'Friday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='routine',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='routine',
            name='startTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_address',
            field=models.CharField(blank=True, max_length=95),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='nfc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=95),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Tutor', 'Tutor')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Fingerprints',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='student_group',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student'),
        ),
        migrations.AddField(
            model_name='student_enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Classroom'),
        ),
        migrations.AddField(
            model_name='attendance_detail',
            name='device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance_detail',
            name='enroll_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student_Enrollment', to_field='enroll_no'),
            preserve_default=False,
        ),
    ]
