# Generated by Django 2.1 on 2018-09-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_auto_20180928_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day_of_the_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=10),
        ),
    ]
