# Generated by Django 2.1 on 2018-09-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_auto_20180928_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_detail',
            name='device_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Device'),
        ),
        migrations.AlterField(
            model_name='attendance_detail',
            name='enroll_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student_Enrollment', to_field='enroll_no'),
        ),
        migrations.AlterField(
            model_name='attendance_detail',
            name='entry_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
